
FROM ubuntu:16.04

##ngraph-part:

RUN apt-get update && apt-get install -y \
        build-essential cmake \
        clang-3.9 clang-format-3.9 \
        git \
        wget patch diffutils zlib1g-dev libtinfo-dev \
        doxygen graphviz \
        python-pip

RUN apt-get clean autoclean && \
    apt-get autoremove -y
RUN pip install --upgrade pip

# need to use sphinx version 1.6 to build docs
# installing with apt-get install python-sphinx installs sphinx version 1.3.6 only
# added install for python-pip above and
# installed sphinx with pip to get the updated version 1.6.5
# allows for make html build under the doc/source directory as an interim build process
RUN pip install sphinx
RUN pip install breathe

# need numpy to successfully build docs for python_api
RUN pip install numpy

# Download and build ngraph
WORKDIR /
RUN rm -rf ngraph && \
  git clone https://github.com/NervanaSystems/ngraph.git && \
  cd ngraph && \
  mkdir build && \
  cd build && \
#  cmake ../ -DNGRAPH_USE_PREBUILT_LLVM=TRUE -DNGRAPH_TARGET_ARCH=skylake-avx512 && \
  cmake ../ -DNGRAPH_USE_PREBUILT_LLVM=TRUE && \
  make -j96 && \
  make install
WORKDIR /ngraph
##end of ngraph-part


RUN apt-get install -y libopencv-dev curl libatlas-base-dev python && \
 apt-get install -y  python-pip python-dev python-opencv graphviz python-scipy python-sklearn libopenblas-dev

WORKDIR /
ENV LD_LIBRARY_PATH=$HOME/ngraph_dist/lib/
RUN rm -rf ngraph-mxnet && \
  git clone --recursive https://github.com/NervanaSystems/ngraph-mxnet && \
  cd ngraph-mxnet && \
  sed '100 c\
  > USE_NGRAPH = 1' make/config.mk && \
  sed '101 c\
  > NGRAPH_DIR = $(HOME)/ngraph_dist' make/config.mk && \
  make -j $(nproc) && \
  cd python && pip install -e . && cd ../
